# Fox and Hound Sales

In [1]:
#import dependencies
import pandas as pd
import numpy as np

In [2]:
#import files
weekbyweek = pd.read_excel("./2021/Week by Week Totals.xlsx", None)

In [3]:
# Check list of sheets
weekbyweek.keys()

dict_keys(['Wkly Totals', 'Wk by Wk', 'Mth by Mth'])

In [4]:
# Sort each sheet to variables 
# print full sheet to get a look at how to clean this up
pd.set_option('display.max_column', None)
pd.set_option('display.max_row', None)
wklytotal = weekbyweek['Wkly Totals']
wkbywk = weekbyweek['Wk by Wk']
mthbymth = weekbyweek['Mth by Mth']

In [5]:
wklytotal.head(9)

,F&H Sales - Weekly Totals,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,F&H Sales - Weekly Totals.1,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,F&H Sales - Weekly Totals.2,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,F&H Sales - Weekly Totals.3,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,NaN,NaN,2017.0,2018.00,2019.00,2020.00,2021.00,NaN,NaN,2017.0,2018.00,2019.00,2020.0,2021.00,NaN,NaN,2017.0,2018.00,2019.00,2020.00,2021.00,NaN,NaN,2017.0,2018.00,2019.00,2020.00,2021.00,NaN,NaN,2018.00,2019.00,2020.00
1,Week 1,M,NaN,0.00,1877.88,1776.24,1855.74,Week 14,M,NaN,1022.30,1742.21,0.0,941.88,Week 27,M,NaN,995.54,1328.89,661.00,1268.63,Week 40,M,NaN,1145.34,1583.50,1164.64,1049.24,Week 53,M,1877.88,1776.24,1370.72
2,NaN,T,NaN,1222.95,0.00,2336.43,1305.33,NaN,T,NaN,1344.93,2088.50,0.0,2697.13,NaN,T,NaN,2718.34,1740.13,659.25,1467.40,NaN,T,NaN,1380.28,1233.85,630.17,1183.11,NaN,T,NaN,2336.43,1211.25
3,NaN,W,NaN,2021.75,2181.72,0.00,2450.89,NaN,W,NaN,2502.53,2430.52,0.0,2365.09,NaN,W,NaN,0.00,2883.23,1058.49,4056.15,NaN,W,NaN,1812.37,1844.71,1794.49,1738.95,NaN,W,NaN,NaN,1838.68
4,NaN,T,NaN,1602.64,1838.60,1456.68,1986.80,NaN,T,NaN,2091.61,2275.52,0.0,2950.96,NaN,T,NaN,1256.79,0.00,1131.74,1432.77,NaN,T,NaN,1698.68,1803.44,1720.08,1848.60,NaN,T,NaN,NaN,2351.71
5,NaN,F,NaN,1896.04,2267.91,1830.02,2574.28,NaN,F,NaN,2402.93,3292.02,0.0,2832.65,NaN,F,NaN,2087.40,2792.09,1521.70,2177.34,NaN,F,NaN,1883.68,1912.03,2195.68,1905.16,NaN,F,NaN,NaN,0.00
6,NaN,S,NaN,3026.82,2209.32,1453.82,2073.30,NaN,S,NaN,1971.25,2284.00,0.0,2479.18,NaN,S,NaN,3464.32,1805.12,0.00,2114.67,NaN,S,NaN,1831.06,2454.55,1149.35,1778.35,NaN,S,NaN,NaN,1929.93
7,NaN,S,NaN,1309.79,1399.46,1516.07,1313.59,NaN,S,NaN,1422.24,2284.14,0.0,1549.35,NaN,S,NaN,1273.07,1636.59,682.45,5116.91,NaN,S,NaN,1010.77,1448.39,1252.83,0.00,NaN,S,NaN,NaN,1108.26
8,NaN,Ttl,NaN,11079.99,11774.89,10369.26,13559.93,NaN,Ttl,NaN,12757.79,16396.91,0.0,15816.24,NaN,Ttl,NaN,11795.46,12186.05,5714.63,17633.87,NaN,Ttl,NaN,10762.18,12280.47,9907.24,9503.41,NaN,Ttl,1877.88,4112.67,9810.55

In [6]:
# List of names for reference 
weekbyweek['Wkly Totals'].columns

Index(['F&H Sales - Weekly Totals', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'F&H Sales - Weekly Totals.1', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'F&H Sales - Weekly Totals.2', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22',
       'F&H Sales - Weekly Totals.3', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32'],
      dtype='object')

In [7]:
# week by week comparison by years
wkbywk.head(9)

,F&H Turnover - Week by Week Comparison,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,2017.0,2018.00,2019.00,2020.00,2021.00
1,Wk 1,NaN,11079.99,11774.89,10369.26,13559.93
2,Wk 2,NaN,14227.18,14677.40,12874.59,11558.62
3,Wk 3,NaN,12245.37,13644.76,12273.52,8998.44
4,Wk 4,NaN,12539.95,14054.31,12124.24,4576.24
5,Wk 5,NaN,12819.22,13754.56,11963.40,10534.43
6,Wk 6,NaN,10654.13,14469.51,12446.39,11735.42
7,Wk 7,NaN,12828.19,15954.74,14411.92,11218.95
8,Wk 8,NaN,13227.18,14945.43,15159.69,12132.85

In [8]:
# month to month comparison by years
# *Note - Contact owner about other business name in the data. may be the wrong sheet or wrong name
mthbymth.head(9)

,Mulligan's Turnover - Week by Week Comparison,Month by Month Comparison,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,2017.0,2018.00,2019.00,2020.00,2021.00
1,January,NaN,54156.07,60143.12,52515.57,41731.42
2,February,NaN,49685.28,59451.23,58518.17,45621.65
3,March,NaN,58872.55,77070.61,33063.66,62648.56
4,April,NaN,51447.97,64712.87,0.00,61265.67
5,May,NaN,52201.58,62557.09,9517.20,57543.31
6,June,NaN,52245.87,57682.84,39853.96,55396.75
7,July,NaN,50897.56,55733.22,20483.45,61034.03
8,August,NaN,46924.70,61266.39,37261.07,39962.50

## Weekly Total Cleanup

In [11]:
wklytotal.fillna(0, inplace = True)
wklytotal.head(9)

,F&H Sales - Weekly Totals,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,F&H Sales - Weekly Totals.1,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,F&H Sales - Weekly Totals.2,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,F&H Sales - Weekly Totals.3,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,0,0,2017.0,2018.00,2019.00,2020.00,2021.00,0,0,2017.0,2018.00,2019.00,2020.0,2021.00,0,0,2017.0,2018.00,2019.00,2020.00,2021.00,0,0,2017.0,2018.00,2019.00,2020.00,2021.00,0,0,2018.00,2019.00,2020.00
1,Week 1,M,0.0,0.00,1877.88,1776.24,1855.74,Week 14,M,0.0,1022.30,1742.21,0.0,941.88,Week 27,M,0.0,995.54,1328.89,661.00,1268.63,Week 40,M,0.0,1145.34,1583.50,1164.64,1049.24,Week 53,M,1877.88,1776.24,1370.72
2,0,T,0.0,1222.95,0.00,2336.43,1305.33,0,T,0.0,1344.93,2088.50,0.0,2697.13,0,T,0.0,2718.34,1740.13,659.25,1467.40,0,T,0.0,1380.28,1233.85,630.17,1183.11,0,T,0.00,2336.43,1211.25
3,0,W,0.0,2021.75,2181.72,0.00,2450.89,0,W,0.0,2502.53,2430.52,0.0,2365.09,0,W,0.0,0.00,2883.23,1058.49,4056.15,0,W,0.0,1812.37,1844.71,1794.49,1738.95,0,W,0.00,0.00,1838.68
4,0,T,0.0,1602.64,1838.60,1456.68,1986.80,0,T,0.0,2091.61,2275.52,0.0,2950.96,0,T,0.0,1256.79,0.00,1131.74,1432.77,0,T,0.0,1698.68,1803.44,1720.08,1848.60,0,T,0.00,0.00,2351.71
5,0,F,0.0,1896.04,2267.91,1830.02,2574.28,0,F,0.0,2402.93,3292.02,0.0,2832.65,0,F,0.0,2087.40,2792.09,1521.70,2177.34,0,F,0.0,1883.68,1912.03,2195.68,1905.16,0,F,0.00,0.00,0.00
6,0,S,0.0,3026.82,2209.32,1453.82,2073.30,0,S,0.0,1971.25,2284.00,0.0,2479.18,0,S,0.0,3464.32,1805.12,0.00,2114.67,0,S,0.0,1831.06,2454.55,1149.35,1778.35,0,S,0.00,0.00,1929.93
7,0,S,0.0,1309.79,1399.46,1516.07,1313.59,0,S,0.0,1422.24,2284.14,0.0,1549.35,0,S,0.0,1273.07,1636.59,682.45,5116.91,0,S,0.0,1010.77,1448.39,1252.83,0.00,0,S,0.00,0.00,1108.26
8,0,Ttl,0.0,11079.99,11774.89,10369.26,13559.93,0,Ttl,0.0,12757.79,16396.91,0.0,15816.24,0,Ttl,0.0,11795.46,12186.05,5714.63,17633.87,0,Ttl,0.0,10762.18,12280.47,9907.24,9503.41,0,Ttl,1877.88,4112.67,9810.55

In [ ]:
# fill new index row with proper names
# drop dead rows with all 0's

In [13]:
wklytotal.columns = np.append(wklytotal.iloc[0, :33].astype('int'), wklytotal.columns[33:])
wklytotal = wklytotal.iloc[1:].reset_index(drop=True) 
wklytotal

,0,0,2017,2018,2019,2020,2021,0,0,2017,2018,2019,2020,2021,0,0,2017,2018,2019,2020,2021,0,0,2017,2018,2019,2020,2021,0,0,2018,2019,2020
0,Week 1,M,0.0,0.00,1877.88,1776.24,1855.74,Week 14,M,0.0,1022.30,1742.21,0.00,941.88,Week 27,M,0.0,995.54,1328.89,661.00,1268.63,Week 40,M,0.00,1145.34,1583.50,1164.64,1049.24,Week 53,M,1877.88,1776.24,1370.72
1,0,T,0.0,1222.95,0.00,2336.43,1305.33,0,T,0.0,1344.93,2088.50,0.00,2697.13,0,T,0.0,2718.34,1740.13,659.25,1467.40,0,T,0.00,1380.28,1233.85,630.17,1183.11,0,T,0.00,2336.43,1211.25
2,0,W,0.0,2021.75,2181.72,0.00,2450.89,0,W,0.0,2502.53,2430.52,0.00,2365.09,0,W,0.0,0.00,2883.23,1058.49,4056.15,0,W,0.00,1812.37,1844.71,1794.49,1738.95,0,W,0.00,0.00,1838.68
3,0,T,0.0,1602.64,1838.60,1456.68,1986.80,0,T,0.0,2091.61,2275.52,0.00,2950.96,0,T,0.0,1256.79,0.00,1131.74,1432.77,0,T,0.00,1698.68,1803.44,1720.08,1848.60,0,T,0.00,0.00,2351.71
4,0,F,0.0,1896.04,2267.91,1830.02,2574.28,0,F,0.0,2402.93,3292.02,0.00,2832.65,0,F,0.0,2087.40,2792.09,1521.70,2177.34,0,F,0.00,1883.68,1912.03,2195.68,1905.16,0,F,0.00,0.00,0.00
5,0,S,0.0,3026.82,2209.32,1453.82,2073.30,0,S,0.0,1971.25,2284.00,0.00,2479.18,0,S,0.0,3464.32,1805.12,0.00,2114.67,0,S,0.00,1831.06,2454.55,1149.35,1778.35,0,S,0.00,0.00,1929.93
6,0,S,0.0,1309.79,1399.46,1516.07,1313.59,0,S,0.0,1422.24,2284.14,0.00,1549.35,0,S,0.0,1273.07,1636.59,682.45,5116.91,0,S,0.00,1010.77,1448.39,1252.83,0.00,0,S,0.00,0.00,1108.26
7,0,Ttl,0.0,11079.99,11774.89,10369.26,13559.93,0,Ttl,0.0,12757.79,16396.91,0.00,15816.24,0,Ttl,0.0,11795.46,12186.05,5714.63,17633.87,0,Ttl,0.00,10762.18,12280.47,9907.24,9503.41,0,Ttl,1877.88,4112.67,9810.55
8,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00
9,Week 2,M,0.0,1559.60,2113.85,1470.74,1238.31,Week 15,M,0.0,1799.80,1494.76,0.00,1470.75,Week 28,M,0.0,1096.10,1309.44,780.27,1083.24,Week 41,M,0.00,1401.59,868.76,804.39,0.00,0,0,0.00,0.00,0.00
10,0,T,0.0,1652.02,1545.20,1325.19,1322.14,0,T,0.0,2009.35,1522.82,0.00,1291.03,0,T,0.0,1497.07,1400.82,0.00,1887.26,0,T,0.00,1571.90,1648.55,1185.29,0.00,0,0,0.00,0.00,0.00
11,0,W,0.0,2940.07,1818.30,2331.95,1823.03,0,W,0.0,2189.40,2336.46,0.00,2273.47,0,W,0.0,3742.26,2834.58,0.00,2307.83,0,W,0.00,2710.61,2297.76,1525.78,0.00,0,0,0.00,0.00,0.00
12,0,T,0.0,2397.74,2179.65,1370.06,2166.32,0,T,0.0,1757.17,2176.84,0.00,1520.55,0,T,0.0,1871.05,1521.42,0.00,2021.88,0,T,0.00,2098.30,1781.38,1569.62,0.00,0,0,0.00,0.00,0.00
13,0,F,0.0,2083.58,2885.72,2545.41,1820.27,0,F,0.0,2452.45,2839.18,0.00,2673.59,0,F,0.0,1880.77,2070.86,0.00,1880.11,0,F,0.00,2502.97,2339.31,1821.42,0.00,0,0,0.00,0.00,0.00
14,0,S,0.0,2307.98,2480.85,2329.35,1724.49,0,S,0.0,2073.17,2360.67,0.00,2941.94,0,S,0.0,2626.33,2338.48,0.00,1898.28,0,S,0.00,1875.68,2252.76,1696.08,0.00,0,0,0.00,0.00,0.00
15,0,S,0.0,1286.19,1653.83,1501.89,1464.06,0,S,0.0,1282.82,1521.32,0.00,1380.06,0,S,0.0,1633.04,1596.50,0.00,1437.59,0,S,0.00,1206.92,1614.69,1267.86,0.00,0,0,0.00,0.00,0.00
16,0,Ttl,0.0,14227.18,14677.40,12874.59,11558.62,0,Ttl,0.0,13564.16,14252.05,0.00,13551.39,0,Ttl,0.0,14346.62,13072.10,780.27,12516.19,0,Ttl,0.00,13367.97,12803.21,9870.44,0.00,0,0,0.00,0.00,0.00
17,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00
18,Week 3,M,0.0,1183.96,1290.25,1179.59,1013.16,Week 16,M,0.0,1588.55,1510.83,0.00,1517.51,Week 29,M,0.0,1370.13,1881.48,0.00,794.46,Week 42,M,0.00,1542.03,1038.72,755.54,0.00,0,0,0.00,0.00,0.00
19,0,T,0.0,1440.63,1453.13,1127.22,1161.60,0,T,0.0,1536.31,1838.64,0.00,1387.40,0,T,0.0,1358.69,956.31,0.00,1639.43,0,T,0.00,1670.83,2047.95,823.19,0.00,0,0,0.00,0.00,0.00
20,0,W,0.0,1507.12,2677.40,1609.68,1354.82,0,W,0.0,1989.60,2869.94,0.00,2518.59,0,W,0.0,2001.99,2284.96,0.00,2554.70,0,W,0.00,1984.29,1632.00,1516.07,0.00,0,0,0.00,0.00,0.00
21,0,T,0.0,2091.92,1773.17,1852.34,1469.60,0,T,0.0,1591.82,2398.62,0.00,2159.37,0,T,0.0,1245.68,1716.54,0.00,1953.89,0,T,0.00,1596.12,1802.01,990.83,0.00,0,0,0.00,0.00,0.00
22,0,F,0.0,2560.39,2460.01,2759.71,1336.43,0,F,0.0,2688.70,2543.74,0.00,2179.31,0,F,0.0,1829.81,2510.54,1638.45,2190.49,0,F,0.00,1908.56,3007.77,1676.10,0.00,0,0,0.00,0.00,0.00
23,0,S,0.0,2059.95,2483.97,2061.43,1172.58,0,S,0.0,1759.94,2954.59,0.00,2431.74,0,S,0.0,2347.44,2024.61,1213.08,2092.69,0,S,0.00,2333.36,2276.66,1357.95,0.00,0,0,0.00,0.00,0.00
24,0,S,0.0,1401.40,1506.83,1683.55,1490.25,0,S,0.0,999.09,1481.02,0.00,951.68,0,S,0.0,937.23,1777.53,410.29,1408.92,0,S,0.00,1505.16,1335.26,1025.05,0.00,0,0,0.00,0.00,0.00
25,0,Ttl,0.0,12245.37,13644.76,12273.52,8998.44,0,Ttl,0.0,12154.01,15597.38,0.00,13145.60,0,Ttl,0.0,11090.97,13151.97,3261.82,12634.58,0,Ttl,0.00,12540.35,13140.37,8144.73,0.00,0,0,0.00,0.00,0.00
26,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00
27,Week 4,M,0.0,1337.97,1194.92,1251.46,907.22,Week 17,M,0.0,1232.53,1304.02,0.00,2001.83,Week 30,M,0.0,1119.12,1446.84,739.65,781.72,Week 43,M,0.00,1527.30,1001.18,713.71,0.00,0,0,0.00,0.00,0.00
28,0,T,0.0,1239.72,1508.36,1553.27,1322.10,0,T,0.0,1374.94,1536.22,0.00,2245.35,0,T,0.0,1101.18,1154.83,635.33,1011.44,0,T,0.00,1286.59,1281.72,734.71,0.00,0,0,0.00,0.00,0.00
29,0,W,0.0,1982.57,2499.65,2192.09,1467.92,0,W,0.0,2014.09,2813.12,0.00,1478.53,0,W,0.0,1561.60,2046.13,887.73,1937.16,0,W,0.00,2546.79,1847.71,1014.36,0.00,0,0,0.00,0.00,0.00
30,0,T,0.0,1753.62,1848.59,1789.63,879.00,0,T,0.0,2010.95,1887.10,0.00,2158.56,0,T,0.0,1518.18,1381.96,672.87,2072.96,0,T,0.00,1404.43,1902.22,1328.61,0.00,0,0,0.00,0.00,0.00
31,0,F,0.0,2410.03,2358.51,2293.58,0.00,0,F,0.0,1496.42,2992.22,0.00,2689.40,0,F,0.0,1825.51,1814.00,1318.04,2346.07,0,F,0.00,2320.82,1948.37,1861.46,0.00,0,0,0.00,0.00,0.00
32,0,S,0.0,2981.81,2664.02,1574.01,0.00,0,S,0.0,1805.48,2652.08,0.00,1962.75,0,S,0.0,1764.41,1971.15,806.43,1664.41,0,S,0.00,2406.23,2579.13,1559.69,0.00,0,0,0.00,0.00,0.00
33,0,S,0.0,834.23,1980.26,1470.20,0.00,0,S,0.0,1258.65,1800.55,0.00,1789.80,0,S,0.0,903.16,1479.27,686.04,1257.97,0,S,0.00,1341.15,1141.89,972.71,0.00,0,0,0.00,0.00,0.00
34,0,Ttl,0.0,12539.95,14054.31,12124.24,4576.24,0,Ttl,0.0,11193.06,14985.31,0.00,14326.22,0,Ttl,0.0,9793.16,11294.18,5746.09,11071.73,0,Ttl,0.00,12833.31,11702.22,8185.25,0.00,0,0,0.00,0.00,0.00
35,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00
36,Week 5,M,0.0,942.73,1584.98,1051.55,1194.81,Week 18,M,0.0,855.67,1155.23,0.00,1417.79,Week 31,M,0.0,1536.81,1112.81,744.34,746.58,Week44,M,0.00,1197.79,1510.79,777.02,0.00,0,0,0.00,0.00,0.00
37,0,T,0.0,1019.51,1832.25,1888.48,1096.88,0,T,0.0,1331.00,2325.99,0.00,1000.40,0,T,0.0,1172.18,2099.76,1344.75,1485.58,0,T,0.00,993.23,1159.66,1468.25,0.00,0,0,0.00,0.00,0.00
38,0,W,0.0,2101.34,2201.34,1478.05,1068.79,0,W,0.0,1866.62,2701.61,0.00,1696.24,0,W,0.0,1687.05,2816.35,1122.84,2386.54,0,W,0.00,2244.98,1791.81,1216.35,0.00,0,0,0.00,0.00,0.00
39,0,T,0.0,2040.47,2251.07,2138.66,1470.05,0,T,0.0,1700.81,2315.87,0.00,1851.79,0,T,0.0,1267.51,1965.09,1398.85,1568.24,0,T,0.00,1241.87,2216.17,2566.51,0.00,0,0,0.00,0.00,0.00
40,0,F,0.0,2964.66,2212.75,2429.89,2281.21,0,F,0.0,1679.85,2422.89,0.00,2225.66,0,F,0.0,2004.26,3142.99,1690.11,1960.22,0,F,0.00,2319.41,1588.01,1921.93,0.00,0,0,0.00,0.00,0.00
41,0,S,0.0,2363.86,2289.37,1561.97,1988.90,0,S,0.0,1838.25,2231.13,0.00,2330.71,0,S,0.0,1935.79,1959.32,1567.07,860.03,0,S,0.00,2368.61,2015.73,2010.95,0.00,0,0,0.00,0.00,0.00
42,0,S,0.0,1386.65,1382.80,1414.80,1433.79,0,S,0.0,1501.06,2428.13,0.00,2083.56,0,S,0.0,798.21,1885.90,686.51,1320.58,0,S,0.00,1448.31,984.78,1125.15,0.00,0,0,0.00,0.00,0.00
43,0,Ttl,0.0,12819.22,13754.56,11963.40,10534.43,0,Ttl,0.0,10773.26,15580.85,0.00,12606.15,0,Ttl,0.0,10401.81,14982.22,8554.47,10327.77,0,Ttl,0.00,11814.20,11266.95,11086.16,0.00,0,0,0.00,0.00,0.00
44,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00
45,Week 6,M,0.0,1030.31,1440.95,1136.47,1123.07,Week 19,M,0.0,1738.32,991.38,0.00,1056.43,Week 32,M,0.0,1283.53,1293.90,821.24,747.03,Week 45,M,0.00,1238.72,1514.51,743.28,0.00,0,0,0.00,0.00,0.00
46,0,T,0.0,1087.76,1490.56,1291.39,1565.04,0,T,0.0,1460.86,1368.20,0.00,1867.44,0,T,0.0,1408.52,1552.03,637.01,1858.20,0,T,0.00,1587.16,1751.50,1166.85,0.00,0,0,0.00,0.00,0.00
47,0,W,0.0,1290.07,1652.36,1631.72,1790.43,0,W,0.0,2121.51,2623.91,0.00,2155.10,0,W,0.0,2081.15,2921.54,1333.12,1959.04,0,W,0.00,1761.23,1530.21,2050.70,0.00,0,0,0.00,0.00,0.00
48,0,T,0.0,2081.81,2266.20,2139.76,1994.96,0,T,0.0,1725.63,1867.02,0.00,2293.06,0,T,0.0,1584.94,1549.15,1049.74,870.71,0,T,0.00,2073.52,2136.42,1545.33,0.00,0,0,0.00,0.00,0.00
49,0,F,0.0,2208.13,2934.22,2868.28,2034.28,0,F,0.0,2000.40,2562.16,0.00,3508.02,0,F,0.0,2417.32,2389.27,1576.28,1558.52,0,F,0.00,3244.70,2374.04,1713.78,0.00,0,0,0.00,0.00,0.00
50,0,S,0.0,1977.60,2594.62,1907.06,2075.49,0,S,0.0,2004.89,2029.48,0.00,1706.13,0,S,0.0,1560.40,2255.66,989.20,781.22,0,S,0.00,1872.28,1972.04,2009.95,0.00,0,0,0.00,0.00,0.00
51,0,S,0.0,978.45,2090.60,1471.71,1152.15,0,S,0.0,2364.80,1795.40,0.00,1422.16,0,S,0.0,971.51,1494.08,925.98,719.53,0,S,0.00,1379.72,1490.99,1311.01,0.00,0,0,0.00,0.00,0.00
52,0,Ttl,0.0,10654.13,14469.51,12446.39,11735.42,0,Ttl,0.0,13416.41,13237.55,0.00,14008.34,0,Ttl,0.0,11307.37,13455.63,7332.57,8494.25,0,Ttl,0.00,13157.33,12769.71,10540.90,0.00,0,0,0.00,0.00,0.00
53,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00
54,Week 7,M,0.0,1251.47,1519.62,1466.89,1201.33,Week 20,M,0.0,928.70,1544.38,0.00,1223.94,Week 33,M,0.0,1070.72,1858.82,823.00,920.81,Week 46,M,0.00,1472.24,988.87,753.80,0.00,0,0,0.00,0.00,0.00
55,0,T,0.0,1380.05,2810.50,1640.34,1739.34,0,T,0.0,1117.70,1500.49,0.00,1645.60,0,T,0.0,1264.23,1555.12,1496.84,841.08,0,T,0.00,1570.93,1430.69,975.67,0.00,0,0,0.00,0.00,0.00
56,0,W,0.0,2322.97,2247.07,2364.69,1378.08,0,W,0.0,2000.21,2173.79,0.00,1953.58,0,W,0.0,1646.74,2096.57,1087.80,1167.54,0,W,0.00,1791.90,1504.52,1988.45,0.00,0,0,0.00,0.00,0.00
57,0,T,0.0,2143.60,2326.42,2435.56,2098.24,0,T,0.0,1857.39,1770.36,0.00,2740.59,0,T,0.0,1384.06,1971.97,1041.89,1943.25,0,T,0.00,2056.47,1961.97,1368.15,0.00,0,0,0.00,0.00,0.00
58,0,F,0.0,2233.27,2112.66,2713.93,2469.02,0,F,0.0,2165.06,2896.23,0.00,2149.85,0,F,0.0,2099.27,2718.67,2187.36,2003.00,0,F,0.00,2378.26,2105.32,1741.45,0.00,0,0,0.00,0.00,0.00
59,0,S,0.0,1797.80,3015.66,2280.45,1551.32,0,S,0.0,1949.80,2120.68,0.00,2566.86,0,S,0.0,1759.83,2341.35,1624.88,1126.16,0,S,0.00,2382.78,1903.55,1716.85,0.00,0,0,0.00,0.00,0.00
60,0,S,0.0,1699.03,1922.81,1510.06,781.62,0,S,0.0,1463.24,1309.50,0.00,1266.75,0,S,0.0,1337.24,1324.29,737.97,1156.33,0,S,0.00,1972.82,1156.64,1311.27,0.00,0,0,0.00,0.00,0.00
61,0,Ttl,0.0,12828.19,15954.74,14411.92,11218.95,0,Ttl,0.0,11482.10,13315.43,0.00,13547.17,0,Ttl,0.0,10562.09,13866.79,8999.74,9158.17,0,Ttl,0.00,13625.40,11051.56,9855.64,0.00,0,0,0.00,0.00,0.00
62,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00
63,Week 8,M,0.0,1401.81,1507.68,1805.69,1489.34,Week 21,M,0.0,1323.14,1209.00,0.00,1378.64,Week 34,M,0.0,1287.92,1151.40,1015.00,827.48,Week 47,M,0.00,1420.87,1618.75,788.43,0.00,0,0,0.00,0.00,0.00
64,0,T,0.0,1212.65,1666.67,1612.55,1350.87,0,T,0.0,1190.38,1709.08,0.00,752.72,0,T,0.0,924.55,1834.18,924.27,1398.00,0,T,0.00,1211.77,1545.85,1218.10,0.00,0,0,0.00,0.00,0.00
65,0,W,0.0,1921.80,2711.96,1800.81,1402.47,0,W,0.0,2151.69,2497.28,0.00,1953.55,0,W,0.0,1599.50,2687.71,1323.06,1510.26,0,W,0.00,2747.38,1439.77,1480.32,0.00,0,0,0.00,0.00,0.00
66,0,T,0.0,1937.69,2508.09,2766.90,2172.08,0,T,0.0,1552.58,1887.86,0.00,2381.43,0,T,0.0,1929.94,1811.37,1661.25,1091.95,0,T,0.00,958.47,1356.07,1473.38,0.00,0,0,0.00,0.00,0.00
67,0,F,0.0,2601.32,2582.46,2958.31,3004.11,0,F,0.0,2060.73,2552.96,0.00,2315.03,0,F,0.0,1964.56,2135.23,1511.23,1462.26,0,F,0.00,2262.99,1751.56,2779.10,0.00,0,0,0.00,0.00,0.00
68,0,S,0.0,2843.92,2460.49,2204.04,1805.01,0,S,0.0,2712.04,2441.55,0.00,3157.20,0,S,0.0,1645.25,2224.23,1511.41,1354.29,0,S,0.00,2175.35,1879.51,2003.65,0.00,0,0,0.00,0.00,0.00
69,0,S,0.0,1307.99,1508.08,2011.39,908.97,0,S,0.0,1194.60,1504.06,0.00,1690.53,0,S,0.0,1339.90,1834.23,968.19,1028.84,0,S,0.00,1909.12,1860.04,467.42,0.00,0,0,0.00,0.00,0.00
70,0,Ttl,0.0,13227.18,14945.43,15159.69,12132.85,0,Ttl,0.0,12185.16,13801.79,0.00,13629.10,0,Ttl,0.0,10691.62,13678.35,8914.41,8673.08,0,Ttl,0.00,12685.95,11451.55,10210.40,0.00,0,0,0.00,0.00,0.00
71,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00
72,Week 9,M,0.0,1207.02,1999.75,1560.14,1884.44,Week 22,M,0.0,1127.60,2238.08,0.00,0.00,Week 35,M,0.0,1121.18,1423.78,795.81,755.72,Week 48,M,0.00,953.13,1220.21,1062.97,0.00,0,0,0.00,0.00,0.00
73,0,T,0.0,1009.37,2006.41,1710.08,1407.75,0,T,0.0,1422.13,1595.88,1979.05,1493.52,0,T,0.0,1010.06,1913.35,902.18,1295.54,0,T,0.00,1056.12,1507.75,1471.36,0.00,0,0,0.00,0.00,0.00
74,0,W,0.0,2003.75,1793.41,2331.66,1603.48,0,W,0.0,1544.29,2063.08,1533.60,1009.23,0,W,0.0,1327.38,1827.77,1470.74,1468.38,0,W,0.00,1729.60,2810.11,2329.59,0.00,0,0,0.00,0.00,0.00
75,0,T,0.0,2211.45,2397.06,2402.07,2189.74,0,T,0.0,1106.30,1997.43,819.91,2150.33,0,T,0.0,1185.75,1943.15,1362.80,1563.34,0,T,0.00,2393.89,0.00,603.92,0.00,0,0,0.00,0.00,0.00
76,0,F,0.0,2294.60,3001.11,2834.78,2120.54,0,F,0.0,2394.19,2208.22,2834.77,2110.98,0,F,0.0,2026.43,1627.23,2134.48,2108.74,0,F,2178.11,2301.77,2398.23,1414.24,0.00,0,0,0.00,0.00,0.00
77,0,S,0.0,2107.92,2466.84,2684.67,1782.07,0,S,0.0,2212.91,3360.11,1472.88,2577.95,0,S,0.0,1484.19,2577.04,1270.22,1898.23,0,S,1702.65,1860.70,1798.48,898.17,0.00,0,0,0.00,0.00,0.00
78,0,S,0.0,1090.44,1501.50,1878.47,2086.17,0,S,0.0,1276.90,1540.77,876.99,1345.09,0,S,0.0,2136.88,2329.49,789.17,1443.14,0,S,1558.17,1414.02,1082.34,1036.63,0.00,0,0,0.00,0.00,0.00
79,0,Ttl,0.0,11924.55,15166.08,15401.87,13074.19,0,Ttl,0.0,11084.32,15003.57,9517.20,10687.10,0,Ttl,0.0,10291.87,13641.81,8725.40,10533.09,0,Ttl,5438.93,11709.23,10817.12,8816.88,0.00,0,0,0.00,0.00,0.00
80,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00
81,Week 10,M,0.0,1423.56,2201.24,1610.19,1908.84,Week 23,M,0.0,1296.42,1482.16,1130.97,1320.83,Week 36,M,0.0,1411.66,1380.92,1035.37,1583.29,Week 49,M,942.48,1190.26,1372.32,1362.19,0.00,0,0,0.00,0.00,0.00
82,0,T,0.0,1217.33,1649.21,1439.36,1287.15,0,T,0.0,1814.59,1459.55,909.70,1882.91,0,T,0.0,1680.70,797.00,775.95,930.24,0,T,1140.03,1206.50,1433.35,1250.03,0.00,0,0,0.00,0.00,0.00
83,0,W,0.0,1700.44,2811.52,2441.88,1795.10,0,W,0.0,1448.88,2448.16,1853.15,2102.38,0,W,0.0,1645.99,2191.33,1356.38,1564.04,0,W,1341.05,2289.80,1503.01,1375.53,0.00,0,0,0.00,0.00,0.00
84,0,T,0.0,2322.13,2747.67,2725.53,2240.35,0,T,0.0,1810.25,2267.12,1278.03,1684.20,0,T,0.0,2025.04,1782.01,1430.05,1478.59,0,T,1292.20,2088.59,1859.49,1752.39,0.00,0,0,0.00,0.00,0.00
85,0,F,0.0,2568.71,2653.60,2940.23,2349.30,0,F,0.0,1967.15,2338.43,1894.42,2745.13,0,F,0.0,1737.16,2611.61,1715.40,2545.97,0,F,1954.57,2514.54,2266.12,2101.87,0.00,0,0,0.00,0.00,0.00
86,0,S,0.0,2422.18,2171.90,2280.36,2091.45,0,S,0.0,1767.30,2291.41,1944.90,2502.59,0,S,0.0,2056.08,2596.29,1400.41,2552.24,0,S,2303.24,2140.08,2142.94,2725.93,0.00,0,0,0.00,0.00,0.00
87,0,S,0.0,1814.96,1890.30,1788.51,1169.69,0,S,0.0,1461.11,1499.47,997.15,2221.21,0,S,0.0,1566.85,1096.32,990.79,1776.76,0,S,1590.90,1605.47,1365.21,901.21,0.00,0,0,0.00,0.00,0.00
88,0,Ttl,0.0,13469.31,16125.44,15226.06,12841.88,0,Ttl,0.0,11565.70,13786.30,10008.32,14459.25,0,Ttl,0.0,12123.48,12455.48,8704.35,12431.13,0,Ttl,10564.47,13035.24,11942.44,11469.15,0.00,0,0,0.00,0.00,0.00
89,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00
90,Week11,M,0.0,1158.08,1971.19,1500.79,1978.18,Week 24,M,0.0,1468.36,1265.94,1699.84,1062.57,Week37,M,0.0,777.62,1087.13,923.96,1144.48,Week 50,M,1545.95,1479.06,1216.44,642.29,0.00,0,0,0.00,0.00,0.00
91,0,T,0.0,1449.80,2135.87,1577.35,2001.26,0,T,0.0,1216.94,1722.71,1287.40,1384.40,0,T,0.0,977.24,1157.75,1161.80,1607.81,0,T,1111.91,1417.42,1399.59,1269.63,0.00,0,0,0.00,0.00,0.00
92,0,W,0.0,1711.84,2503.98,2401.17,4378.85,0,W,0.0,1912.10,2365.80,1631.86,2229.21,0,W,0.0,1634.65,1745.16,1268.13,1714.08,0,W,1832.72,2705.21,1581.79,1669.57,0.00,0,0,0.00,0.00,0.00
93,0,T,0.0,2338.18,2741.56,2523.64,1675.30,0,T,0.0,1918.71,2300.13,1613.29,1889.18,0,T,0.0,1410.54,2188.41,1184.55,1888.67,0,T,1564.11,1953.36,1540.56,1481.80,0.00,0,0,0.00,0.00,0.00
94,0,F,0.0,2205.39,3227.86,2036.64,2612.04,0,F,0.0,2266.24,1860.00,2006.54,3240.95,0,F,0.0,2034.98,2629.30,2157.02,1947.76,0,F,3618.44,2040.82,2407.26,1429.76,0.00,0,0,0.00,0.00,0.00
95,0,S,0.0,4426.94,3479.47,1950.18,2266.15,0,S,0.0,1848.83,1647.05,1847.01,2424.47,0,S,0.0,1754.20,2416.70,1326.44,2283.41,0,S,2533.11,1749.29,2037.28,1963.76,0.00,0,0,0.00,0.00,0.00
96,0,S,0.0,1134.90,5569.07,1411.40,1450.91,0,S,0.0,1292.59,1597.82,1434.78,1565.88,0,S,0.0,1231.58,1527.53,1001.78,1327.15,0,S,1568.08,1623.79,1712.92,1213.83,0.00,0,0,0.00,0.00,0.00
97,0,Ttl,0.0,14425.13,21629.00,13401.17,16362.69,0,Ttl,0.0,11923.77,12759.45,11520.72,13796.66,0,Ttl,0.0,9820.81,12751.98,9023.68,11913.36,0,Ttl,13774.32,12968.95,11895.84,9670.64,0.00,0,0,0.00,0.00,0.00
98,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00
99,Week 12,M,0.0,1250.19,1595.11,1304.09,1344.83,Week 25,M,0.0,2122.68,1715.92,704.87,509.52,Week 38,M,0.0,1071.92,1132.65,592.47,1292.37,Week 51,M,997.55,2598.24,1143.27,805.92,0.00,0,0,0.00,0.00,0.00
100,0,T,0.0,1518.01,2045.64,1253.87,2175.32,0,T,0.0,1576.86,1586.65,953.95,1565.98,0,T,0.0,1206.92,1322.61,655.27,964.79,0,T,1334.83,1684.71,1403.66,1265.15,0.00,0,0,0.00,0.00,0.00
101,0,W,0.0,1683.53,3012.08,0.00,2006.27,0,W,0.0,2300.91,2916.21,1316.11,1754.80,0,W,0.0,1181.72,1834.45,1218.60,3171.20,0,W,2030.82,1929.30,1774.66,952.37,0.00,0,0,0.00,0.00,0.00
102,0,T,0.0,2328.36,2644.66,0.00,2323.69,0,T,0.0,1862.55,1862.95,1364.05,2228.37,0,T,0.0,1491.69,2140.47,1127.46,1664.52,0,T,1794.55,2081.40,1673.82,1673.75,0.00,0,0,0.00,0.00,0.00
103,0,F,0.0,2560.84,2715.21,0.00,2795.99,0,F,0.0,2266.83,2366.56,1582.68,1643.38,0,F,0.0,1411.09,2298.79,1494.78,1989.65,0,F,1506.33,2869.45,1744.71,2043.58,0.00,0,0,0.00,0.00,0.00
104,0,S,0.0,2377.53,2976.26,0.00,2618.30,0,S,0.0,1541.94,1819.20,1883.66,2017.08,0,S,0.0,1841.98,2042.06,1500.97,3311.91,0,S,1594.81,2086.04,1400.18,924.43,0.00,0,0,0.00,0.00,0.00
105,0,S,0.0,1403.96,2340.18,0.00,1377.20,0,S,0.0,2019.80,1438.70,702.31,1166.24,0,S,0.0,987.93,1597.37,1043.68,951.32,0,S,1766.51,1856.09,1648.09,1211.76,0.00,0,0,0.00,0.00,0.00
106,0,Ttl,0.0,13122.42,17329.14,2557.96,14641.60,0,Ttl,0.0,13691.57,13706.19,8507.63,10885.37,0,Ttl,0.0,9193.25,12368.40,7633.23,13345.76,0,Ttl,11025.40,15105.23,10788.39,8876.96,0.00,0,0,0.00,0.00,0.00
107,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00
108,Week 13,M,0.0,1179.61,1696.88,0.00,1608.67,Week 26,M,0.0,1100.67,1649.93,1218.81,1283.94,Week 39,M,0.0,1263.97,1185.41,1107.26,960.16,Week 52,M,0.00,1846.98,1787.05,1760.76,0.00,0,0,0.00,0.00,0.00
109,0,T,0.0,1194.55,1420.16,0.00,1748.11,0,T,0.0,1453.67,1149.70,1222.25,2067.37,0,T,0.0,1234.33,1188.78,787.56,916.36,0,T,1758.21,0.00,1670.60,1050.50,0.00,0,0,0.00,0.00,0.00
110,0,W,0.0,2063.12,2663.67,0.00,2371.42,0,W,0.0,1586.79,2012.98,979.39,2217.06,0,W,0.0,2071.70,1959.49,1546.83,1633.25,0,W,2183.35,3446.22,0.00,1590.23,0.00,0,0,0.00,0.00,0.00